name: Build and Release Plugin

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Build plugin
      run: ./gradlew buildPlugin
      
    - name: Get version from gradle
      id: get_version
      run: echo "VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')" >> $GITHUB_OUTPUT
      
    - name: Upload plugin to release
      uses: softprops/action-gh-release@v2
      with:
        files: ./build/distributions/go-bdd-goland-${{ steps.get_version.outputs.VERSION }}.zip